version: "3"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.2.0/24

services:
           
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall1
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_PATH}/heimdall:/config
    ports:
      - 60211:443
    networks:
      network:
        ipv4_address: 172.128.2.11

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 60213:8191
    networks:
      network:
        ipv4_address: 172.128.2.13
 
  jproxy:
    image: mxy6662/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jproxy/database:/app/database
    ports:
      - 60215:8117
    networks:
      network:
        ipv4_address: 172.128.2.15

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr1
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - JELLYFIN_TYPE=emby
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - 60216:5055
    networks:
      network:
        ipv4_address: 172.128.2.16
    depends_on:
      - sonarr
      - radarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr1
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60217:7878
    networks:
      network:
        ipv4_address: 172.128.2.17
    depends_on:
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr1
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60218:8989
    networks:
      network:
        ipv4_address: 172.128.2.18
    depends_on:
      - qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent1
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=60219
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60219:60219
      - 60881:6881
      - 60881:6881/udp
    networks:
      network:
        ipv4_address: 172.128.2.19

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    container_name: chinesesubfinder1
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/chinesesubfinder:/config
      - ${MEDIA_PATH}:/media/video
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PERMS=true
      - UMASK=022
      - HTTP_PROXY=http://172.128.2.25:7890
      - NO_PROXY=172.128.2.20
    hostname: chinesesubfinder
    ports:
      - 60221:19035
      - 19037:19037
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      network:
        ipv4_address: 172.128.2.21

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 60223:9696
    networks:
      network:
        ipv4_address: 172.128.2.23

  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    restart: always
    ports:
      - '7100:80'
    networks:
      network:
        ipv4_address: 172.128.2.24

  meta:
    container_name: meta
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    volumes:
      - ${CONFIG_PATH}/mihomo:/root/.config/mihomo
    ports:
      - '9090:9090'
      - '7890:7890/tcp'
      - '7890:7890/udp'
    networks:
      network:
        ipv4_address: 172.128.2.25

  emby:
    image: linuxserver/emby:4.8.7.0
    container_name: emby1
    restart: unless-stopped
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=${TZ}
      - HTTP_PROXY=http://172.128.2.25:7890
      - NO_PROXY=172.128.2.20,172.128.2.21  
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60220:8096
    networks:
      network:
        ipv4_address: 172.128.2.20
