mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://dns.alidns.com/dns-query#h3=true
    - https://doh.pub/dns-query
proxy-providers:
  Flower:
    type: http
    # 修改为你的 Clash 订阅链接
    url: https://onlysub.mjurl.com/api/v1/client/subscribe?token=27ea8137c168b95e3e343405bfc8833d
    path: ./profiles/flower.yml
    interval: 86400
    health-check:
      enable: true
      interval: 3600
      url: https://www.gstatic.com/generate_204
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 故障转移
      - 新加坡节点
      - 香港节点
      - 日本节点
      - 美国节点
      
  - name: 新加坡节点
    type: url-test
    tolerance: 100
    interval: 3600
    lazy: true
    use:
      - Flower
    filter: "(?i)(新加坡)"
    
  - name: 香港节点
    type: url-test
    tolerance: 100
    interval: 3600
    lazy: true
    use:
      - Flower
    filter: "(?i)(港|HK|Hong Kong|Hong)"

  - name: 日本节点
    type: url-test
    tolerance: 100
    interval: 3600
    lazy: true
    use:
      - Flower
    filter: "(?i)(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)"
    
  - name: 美国节点
    type: url-test
    tolerance: 100
    interval: 3600
    lazy: true
    use:
      - Flower
    filter: "(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States)"
    
  - name: 全球直连
    type: select
    proxies:
      - DIRECT
      - 节点选择
      
  - name: 故障转移
    type: fallback
    proxies:
      - 新加坡节点
      - 香港节点
      - 日本节点
      - 美国节点
    interval: 60  # 设置故障转移的时间间隔
    url: https://www.gstatic.com/generate_204
rule-providers:

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,全球直连
  - DOMAIN,clash.razord.top,全球直连
  - DOMAIN,yacd.haishan.me,全球直连
  - RULE-SET,private,全球直连
  - RULE-SET,icloud,全球直连
  - RULE-SET,apple,全球直连
  - RULE-SET,direct,全球直连
  - RULE-SET,lancidr,全球直连
  - RULE-SET,cncidr,全球直连
  - RULE-SET,google,节点选择
  - RULE-SET,gfw,节点选择
  - RULE-SET,greatfire,节点选择
  - RULE-SET,proxy,节点选择
  - RULE-SET,telegramcidr,节点选择
  - RULE-SET,telegramcidr,节点选择
  - GEOIP,LAN,全球直连
  - GEOIP,CN,全球直连
  - MATCH,节点选择
